create table EMPLOYEE_ADDRESS
(
 ID  INT NOT NULL AUTO_INCREMENT,
 EMP_ID INT NOT NULL,
 ADDRESS_LINE_1 varchar(50) NOT NULL,
 ADDRESS_LINE_2 varchar(50),
 CITY varchar(50) NOT NULL,
 STATE varchar(50) NOT NULL,
 COUNTRY varchar(4) NOT NULL,
 ZIP_CODE varchar(10),
 INDEX emp_ind (EMP_ID),
 CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMP_ID)
  REFERENCES EMPLOYEE(ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  PRIMARY KEY (ID)
);